#!/bin/bash
self_dir=`dirname "$(readlink -f $0)"`
source ${self_dir}/utils.sh
source ~pi/.params
check_internet 5 5 && \
echo url="https://www.duckdns.org/update?domains=$HOST&token=$TOKEN&ip=" | curl -k -o /tmp/duck.log -K - &>/dev/null
