#!/bin/bash
PIDFILE=/tmp/upload.pid
self_dir=`dirname "$(readlink -f $0)"`
source ${self_dir}/utils.sh
source ~pi/.params
export DB
MAX_RETRIES=5

remove() {
  sql "UPDATE files SET state=1 WHERE filename='$1'"
}

if [ ! -f $DB ];then
  sql "create table files (filename TEXT PRIMARY KEY NOT NULL, state INTEGER, mtime INTEGER)"
fi

if [ -r $PIDFILE ];then
  OLDPID=`cat $PIDFILE`
  if kill -0 $OLDPID &>/dev/null;then
    echo "Uploader is still running! ($OLDPID)" >/tmp/upload.$$
    exit -1
  fi 
fi

echo $$ >$PIDFILE

echo "Environment: scandir: '$DIR' ftp server: '$FTP'"
if [ -z "$FTP" -o -z "$DIR" ];then
  echo "Set environment!"
  exit -1
fi

upload_file() {
    FILE=$1
    MTIME=`stat "$FILE" --printf "%Y"`
    SIZE=`stat "$FILE" --printf "%s"`
    NEWNAME=${PREFIX}`date --date=@$MTIME "+%Y%m%d_%H%M%S"`.mp4
    echo "Uploading $FILE with new name $NEWNAME"
    curl -s --tcp-nodelay -n -T $FILE ftp://$FTP/$NEWNAME && remove $FILE
    if [ $? == 0 ];then
        echo "Upload OK"
        successful=$[ $successful +1 ]
        bytes=$[ $bytes + $SIZE ]
        return 0
    else
        echo "Upload FAILED"
        failed=$[ $failed +1 ]
        return -1
    fi
}

hbytes() {
    echo $1|numfmt --to=si --suffix=b
}

successful=0
failed=0
bytes=0
stime=`date "+%s"`
retries=0
if [ $# -gt 0 ];then
    msg "Uploading $# files"
    while [ $# -gt 0 ];do
        if [ -f $1 ];then 
            upload_file $1
        fi
        shift
    done
else
    BEFORE=`filecount`
    ${self_dir}/findsort.py $DIR
    FILECOUNT=`filecount`
    msg "Found $[ $FILECOUNT - $BEFORE ] new files to upload."
    while [ `filecount` -gt 4 ] && [ $retries -lt $MAX_RETRIES ]; do
      FILE=`sql "SELECT filename FROM files WHERE state=0 ORDER BY mtime LIMIT 1"`
      if upload_file $FILE;then
        retries=0
      else
        retries=$[ $retries + 1 ]
      fi
    done
fi
etime=`date "+%s"`
duration=$[ $etime - $stime ]
days=$[ `date -u -d @${duration} "+%j"` -1 ]
time_str=`date -u -d @${duration} +"%T"`
if [ $days -gt 0 ];then
    duration_str="$days days $time_str"
else
    duration_str=$time_str
fi
if [ $duration -eq 0 ];then
    avg_speed="N/A"
else
    avg_speed="`hbytes $[ $bytes / $duration ]`/sec"
fi
bytes=`hbytes $bytes`
msg "Upload statistics: successful attempts: $successful failed attempts: $failed uploaded: ${bytes} in $duration_str avg speed: ${avg_speed}"
rm $PIDFILE

