#!/bin/bash
SBNAME="$1"
shift
DIR="$HOME/winesandbox/${SBNAME}"
mkdir -p "$DIR"
docker run -it --rm \
  --workdir /home/user0 \
  --user $UID \
  -v "$DIR":/home/user0/ \
  -v /run/user/$UID/pulse/native:/tmp/pulseaudio.socket \
  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix \
  --device /dev/dri \
  --device /dev/snd \
  --privileged \
"$@" wine-sandbox-staging
